root = "."
tmp_dir = ".bin"

[build]
  bin = "./.bin/arcane"
  cmd = "CGO_ENABLED=1 go build -tags 'exclude_frontend' -ldflags='-buildid=' -o ./.bin/arcane ./cmd"
  exclude_dir = [".bin", "data", "node_modules", ".git"]
  stop_on_error = true
  delay = 500
  exclude_regex = ["_test.go", "_mock.go", ".*_test\\.go$"]
  exclude_unchanged = true
  follow_symlink = false
  include_ext = ["go", "tpl", "tmpl", "html"]
  kill_delay = "2s"
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  rerun = false
  rerun_delay = 300
  send_interrupt = true
  stop_on_root = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = true

[misc]
  # Preserves incremental builds
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
  keep_scroll = true